---

stages:
  - build
  - deploy

before_script:
  - "docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}"
  - "docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} docker.magnifico.pro"

build_docker_images:
  stage: build
  script:
    - "docker-compose build"

push_docker_images:
  stage: deploy
  script:
    - "CI_COMMIT_REF_NAME='' docker-compose build"
    - "CI_COMMIT_REF_NAME='' docker-compose push"
