---

stages:
  - build
  - deploy

before_script:
  - "docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} docker.magnifico.pro"

build_docker_images:
  stage: build
  script:
    - "DOCKER_IMAGE_TAG=:${CI_COMMIT_REF_NAME} docker-compose build"

push_docker_images:
  stage: deploy
  script:
    - "DOCKER_IMAGE_TAG='' docker-compose build"
    - "DOCKER_IMAGE_TAG='' docker-compose push"
