---

version: "2"

services:
  memcache:
    image: "magnifico/bitrix:memcache${CI_COMMIT_REF_NAME}"
    build: { context: "./memcache", args: { CI_JOB_ID: "${CI_JOB_ID}" } }

  mysql:
    image: "magnifico/bitrix:mysql${CI_COMMIT_REF_NAME}"
    build: { context: "./mysql", args: { CI_JOB_ID: "${CI_JOB_ID}" } }

  nginx:
    image: "magnifico/bitrix:nginx${CI_COMMIT_REF_NAME}"
    build: { context: "./nginx", args: { CI_JOB_ID: "${CI_JOB_ID}" } }

  phpfpm_70:
    image: "magnifico/bitrix:phpfpm7.0${CI_COMMIT_REF_NAME}"
    build: { context: "./phpfpm/7.0", args: { CI_JOB_ID: "${CI_JOB_ID}" } }

  phpfpm_56:
    image: "magnifico/bitrix:phpfpm5.6${CI_COMMIT_REF_NAME}"
    build: { context: "./phpfpm/5.6", args: { CI_JOB_ID: "${CI_JOB_ID}" } }

  redis:
    image: "magnifico/bitrix:redis${CI_COMMIT_REF_NAME}"
    build: { context: "./redis", args: { CI_JOB_ID: "${CI_JOB_ID}" } }

  sphinx:
    image: "magnifico/bitrix:sphinx${CI_COMMIT_REF_NAME}"
    build: { context: "./sphinx", args: { CI_JOB_ID: "${CI_JOB_ID}" } }

  apache:
    image: "magnifico/bitrix:apache${CI_COMMIT_REF_NAME}"
    build: { context: "./apache", args: { CI_JOB_ID: "${CI_JOB_ID}" } }
